FORMAT: 1A
HOST: https://invacaretest-a493523.integration.us2.oraclecloud.com:443/integration/flowapi/rest/PRODUCTAVAILABILITY/v01/

# Product Availability

Product availability will return the quantity available for the requested items.
The parameters required can be viewed below.

## Product Quantity [/product/getqty{item_id}{item_name}{org_id}{organization_id}]
The source is OCC and target is EBS.
### Get Quantity  [GET]

+ Request
    + Headers

            Authorization: Basic aW52YWNhcmVhZG1pbjpBcnlTaGxDbGQyMDE3

+ Parameters
    + item_id           (string)
    + item_name         (string)
    + org_id            (string)
    + organization_id   (string)


+ Response 200 (application/json)

        {
            "product":
                {
                    "item_id": "",
                    "item_name": "6291-A",
                    "qty": 300
                }
        }
